platform :osx, '10.14'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'ephemeral', 'Flutter-Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure \"flutter pub get\" is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Flutter-Generated.xcconfig, then run \"flutter pub get\""
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_macos_podfile_setup
def flutter_install_ios_plugin_pods(ios_application_path = nil)
  raise 'No se encontró la ruta de la aplicación iOS' unless ios_application_path

  # Agrega esta línea para cada plugin que requiera un Pod
  pod 'flutter_barcode_scanner', :path => '../node_modules/flutter_barcode_scanner/ios'

  # Otras dependencias de los plugins de Flutter pueden ir aquí

  # Si usas Firebase plugins:
  # pod 'Firebase/Analytics'
  # pod 'Firebase/Auth'
  # ...

  # Configuración adicional de Pods según tus necesidades

end
target 'Runner' do
  use_frameworks!
  # Llama a la función que agrega las dependencias de los plugins de Flutter
  flutter_install_ios_plugin_pods(File.dirname(File.realpath(__FILE__)))

  use_modular_headers!

  flutter_install_all_macos_pods File.dirname(File.realpath(__FILE__))
  target 'RunnerTests' do
    inherit! :search_paths
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_macos_build_settings(target)
  end
end
